- name: 'Wordpress download'
  get_url:
    url: https://wordpress.org/wordpress-5.1.12.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: 'Wordpress extraction'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Wordpress configuration file copy'
  copy:
    src: '{{ wordpress_home_path }}/wp-config-sample.php'
    dest: '{{ wordpress_home_path }}/wp-config.php'
    remote_src: yes
  become: yes

- name: 'Wordpress configuration file edition'
  replace:
    path: '{{ wordpress_home_path }}/wp-config.php'
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
  with_items:
    - { regex: 'database_name_here', value: '{{ wordpress_database_name }}' }
    - { regex: 'username_here', value: '{{ wordpress_database_username }}' }
    - { regex: 'password_here', value: '{{ wordpress_database_password }}' }
    - { regex: 'localhost', value: '{{ database_address }}' }
  become: yes

- name: 'Apache configuration file copy'
  template:
    src: templates/apache2/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - 'Apache restart'
