- name: 'install dependencies'
  apt:
    name: [
      mysql-server-5.6,
      python-mysqldb
    ]
    state: latest
    update_cache: yes
  become: yes

- name: 'MySQL database creation'
  mysql_db:
    name: '{{ wordpress_database_name }}'
    login_user: root
    state: present

- name: 'MySQL user creation'
  mysql_user:
    name: '{{ wordpress_database_username }}'
    password: '{{ wordpress_database_password }}'
    priv: '{{ wordpress_database_name }}.*:ALL'
    login_user: root
    state: present
    host: '{{ item }}'
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wordpress_address }}'

- name: 'MySQL configuration file copy'
  copy:
    src: config/my.cnf
    dest: /etc/mysql/
  become: yes
  notify:
    - 'MySQL restart'
